# (c) 2016 DataNexus Inc.  All Rights Reserved
---
# Get the AWS credentials associated with the `post_install_task.ec2_region`
# from the `post_install_task.credentials_file`
- block:
  - set_fact:
      section_filt_str: "{{((post_install_task.ec2_region | default('')) != '') | ternary(' section=' + post_install_task.ec2_region, '')}}"
  - name: Set facts for AWS credentials from credentials file
    set_fact:
      aws_access_key_id: "{{lookup('ini', 'aws_access_key_id' + section_filt_str + ' file=' + post_install_task.credentials_file)}}"
      aws_secret_access_key: "{{lookup('ini', 'aws_secret_access_key' + section_filt_str + ' file=' + post_install_task.credentials_file)}}"
  run_once: true
