#!/usr/bin/env ansible-playbook
#
# (c) 2016 DataNexus Inc.  All Rights Reserved
---
# Build our kafka and zookeeper host groups
- name: Create kafka and zookeeper host groups
  hosts: localhost
  gather_facts: no
  vars_files:
    - vars/kafka-operations.yml
  tasks:
    # load the 'configuration file' (if one was defined) to get any variables
    # we might need during this playbook run
    - name: Load configuration file
      include_vars:
        file: "{{config_file | default('config.yml')}}"
    # then, build our kafka and zookeeper host groups
    - include_role:
        name: build-app-host-groups
      vars:
        host_group_list:
          - name: kafka
          - name: zookeeper
      when: cloud is defined and (cloud == 'aws' or cloud == 'osp')
    - set_fact:
        num_kafka_nodes: "{{groups['kafka'] | default([]) | length}}"
    # if we didn't find any nodes in the kafka host group, then it's an error
    - name: Fail playbook run if a Kafka instance/cluster not found
      fail:
        msg: "An (external) Kafka cluster is required for telegraf deployments"
      when: num_kafka_nodes | int == 0

# Collect some Zookeeper related facts and determine the "private" IP addresses of
# the nodes in the Zookeeper ensemble (from their "public" IP addresses and the `data_iface`
# variable that was passed in as part of this playbook run) if a list of "public"  Zookeeper
# IP addresses was passed in.
- name: Gather facts from Zookeeper host group (if defined)
  hosts: zookeeper
  tasks: []

# If we're adding/removing topics, then connect to the Kafka cluster and perform the
# necessary actions to do so
- name: Configure Kafka topics
  hosts: kafka
  gather_facts: no
  vars_files:
    - vars/kafka-operations.yml
  vars:
    - kafka_nodes: "{{groups['kafka']}}"
    - zookeeper_nodes: "{{groups['zookeeper']}}"
  pre_tasks:
    # first, initialize the play by loading any `config_file` that may have
    # been passed in, determining the `data_iface` and `api_iface` values from
    # the input `internal_subnet` and `external_subnet` (if values for these
    # two parameters were passed in), and determining the addresses of the
    # `data_iface` and `api_iface` interfaces (the `data_addr` and `api_addr`
    # values)
    - include_role:
        name: initialize-play
      vars:
        skip_network_restart: true
    # and now that we know we have our data_iface identified, we can construct
    # the list of zk_nodes (the data_iface IP addresses of our zookeeper_nodes)
    - set_fact:
        zk_nodes: "{{(zookeeper_nodes | default([])) | map('extract', hostvars, [('ansible_' + data_iface), 'ipv4', 'address']) | list}}"
    # Now that we have all of the facts we need we can proceed to modify the topics
    # if that's what we're doing (add new topics to or remove existing topics from
    # the cluster)
    - name: Modify topics
      include_role:
        name: modify-topics
      vars:
        action_hash: "{{list_item}}"
      with_items: "{{action_list}}"
      loop_control:
        loop_var: list_item
